// Auto-generated by scripts/process-docs.mjs
// Do not edit manually.
export const ragContent = `
--- START DOCUMENT: Bachelor Thesis.pdf ---
U N I V E R S I T Y O F C O P E N H A G E N
F A C U L T Y O F S O C I A L S C I E N C E S
Bachelor thesis
The Global Financial Cycle Revisited
The Spillover Effects of US Monetary Policy to the Global Economy
Anton Meier Ebsen Jørgensen
Supervisor: Henrik Jensen
Submitted: May 3, 2024
Number of characters: Approximately 43,510 (18.12 normal pages)
-- 1 of 43 --
Abstract
This thesis analyzes the effects of the monetary policy spillovers from the
US on the global economy. I use a recursive VAR with seven variables
influenced by Rey’s (2013) seminal paper to answer my research question.
While Rey (2013) focuses on the period 1990Q1-2012Q4, my period is
2001Q4-2023Q3 and analyze if my results differ from hers. The variable
for the US monetary policy shock is the short-term interest rate, the ef-
fective federal funds rate. By estimating impulse response functions, I
analyze how a shock to the effective federal funds rate impacts the global
risk, as measured by the VIX. Also, how the VIX impacts the global fi-
nancial cycle. The variables for the global financial cycle of the recursive
VAR’s are the leverage of European banks, global domestic credit, and
cross-border credit flows (Rey, 2013).
The findings of my thesis points to continued existence of monetary policy
spillovers from the US to the global economy. However, the spillovers are
smaller in the COVID-19 period possible due to more efficient regulation.
A US monetary loosening, for instance, is found to decrease global risk,
thereafter increasing the leverage for European banks. However, in the
COVID-19 sample, a lower global risk will result in lower global domestic
credit and lower cross-border credit flows. These newer results might be
a result of the increased regulations to reduce excessive risk-taking (Saft,
2016). My results highlights the crucial role of US monetary policy in
creating financial stability of the global economy.
Keywords: Financial integration, Monetary Policy Spillovers, The Global
Financial Cycle.
JEL classification: E52, E58, F02, F33, G15
2
-- 2 of 43 --
Contents
1 Introduction 4
2 Macroeconomic background 6
2.1 The methodological issues . . . . . . . . . . . . . . . . . . . . . . 6
2.2 The Global Financial Cycle . . . . . . . . . . . . . . . . . . . . . 6
2.3 The international transmission channels of monetary policy . . . 6
2.4 Optimal monetary policy in an interconnected world . . . . . . . 7
3 Description of Data 8
3.1 The Effective Federal Funds Rate (EFFR) . . . . . . . . . . . . . 8
3.2 CBOE Volatility Index (VIX) . . . . . . . . . . . . . . . . . . . . 8
3.3 European Banking Sector Leverage (EULEV) . . . . . . . . . . . 8
3.4 Descriptive statistics of the variables . . . . . . . . . . . . . . . . 9
4 Econometric model 10
4.1 Reduced form Vector Autoregression . . . . . . . . . . . . . . . . 10
4.2 Inference . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 10
4.3 Structural Vector Autoregression . . . . . . . . . . . . . . . . . . 11
4.4 Cholesky decomposition . . . . . . . . . . . . . . . . . . . . . . . 11
4.4.1 Advantages and limitations of the recursive VAR . . . . . 12
4.5 Structural Impulse Response Functions . . . . . . . . . . . . . . . 13
4.5.1 Bootstrap estimation of confidence intervals . . . . . . . . 13
5 Empirical results 14
5.1 Unit root analysis . . . . . . . . . . . . . . . . . . . . . . . . . . 14
5.2 Estimation of the reduced-form VAR . . . . . . . . . . . . . . . . 14
5.2.1 Misspecification tests . . . . . . . . . . . . . . . . . . . . . 15
5.3 The structural impulse response functions . . . . . . . . . . . . . 15
5.4 Empirical findings . . . . . . . . . . . . . . . . . . . . . . . . . . 17
5.5 The impact of a US monetary policy shock on the VIX . . . . . . 17
6 Robustness 19
7 Discussion 20
7.1 The propagation of a US monetary policy shock . . . . . . . . . . 20
7.2 Is the VIX dead? . . . . . . . . . . . . . . . . . . . . . . . . . . . 20
7.3 The size of the US monetary policy spillovers . . . . . . . . . . . 21
7.4 Criticisms of my analysis . . . . . . . . . . . . . . . . . . . . . . . 22
8 Conclusion 23
3
-- 3 of 43 --
1 Introduction
In the decades after a harsh period with the Great Depression and two world
wars, financial integration seemed to be a blast from the past. However, since
1990, policymakers have again worked to open the financial markets to other
countries (Rey, 2013). Financial integration might be here to stay and will play
a more significant role in the future, especially with the potential expansion of
the EU. This realization raises an exciting question for tomorrow’s policymak-
ers: Is financial integration merely a bed of roses, or are there some negative
consequences? The Global Financial Crisis shattered the international consen-
sus that financial integration was a win-win game. Academic discussions on
the potential effects resurfaced, and a new aspect emerged: the loss of financial
stability. Hence, I aim to answer the same question Rey (2013) raises: ”How
does the US monetary policy affect the global financial cycle?” And: ”Are the
monetary policy spillover effects still as large as in Rey (2013)?”
H´el\`ene Rey’s (2013) research found that European economies experienced spillover
effects from US monetary policy through the global risk measured by the VIX to
the leverage of the European banks. Her results became a beacon of academic
recognition. Her analysis, focused on the Global Financial Crisis, was interna-
tionally acknowledged by academic peers and international organizations such
as the IMF, further highlighting the importance of her findings. The US mone-
tary policy propagates to the global financial cycle via the risk-taking channel
of monetary policy (Bruno & Shin, 2012). In some countries, the US monetary
policy spillover effects are even larger than the domestic effects in the US (Geor-
giadis, 2015).
Since Rey’s (2013) important work, many economic events have occurred, most
notably the COVID-19 crisis and the Russian Invasion of Ukraine. The macroe-
conomic tools have also changed, with policymakers focusing more on regulation
and macroprudential policies. It would be interesting to update Rey’s (2013)
recursive VAR with newer data and analyze if her conclusions have changed.
To answer the research question, I take considerable inspiration from Rey’s
(2013) recursive VAR. However, I use data for the period 2001Q4-2023Q3. The
structural shocks in the recursive VAR are derived using Cholesky decomposi-
tion, with the variables ordered higher being: European banking sector leverage,
the effective federal funds rate, and the volatility index, the VIX. From the or-
thogonalized errors, I estimate structural impulse response functions (Killian &
L¨utkepohl, 2016). From the shocks to the system, I analyze how the variables
for the global financial cycle respond to a FED loosening.
My empirical findings point to the importance of US monetary policy in de-
termining the global financial cycle but to a lesser extent than in Rey’s (2013)
recursive VAR. A US monetary policy shock will propagate to the global econ-
omy via the global financial cycle. The propagation is as follows: a US mone-
tary policy loosening will decrease global market risk measured by the VIX. If
the VIX decreases, then the European Banking Sector Leverage will increase.
However, the US monetary policy spillovers are lower in the COVID-19 period.
Moreover, an increase in the leverage of the European banks further lowers the
4
-- 4 of 43 --
VIX. Furthermore, the decrease in the VIX will decrease both the credit inflow
and global domestic credit. These latter two results differ from Rey’s (2013)
findings, as she finds that a decrease in the VIX will increase credit and credit in-
flow. These new dynamics and the lower US monetary spillover effects might be
due to more developed international financial markets because of more efficient
regulation (Saft, 2016). Additionally, I find that higher leverage for European
banks and credit growth will lead to a fall in the VIX. This result is consistent
with the risk-taking channel of monetary policy (Bruno & Shin, 2012).
5
-- 5 of 43 --
2 Macroeconomic background
This section provides an overview of the empirical studies that have shaped my
analysis and influenced the academic research on US monetary policy spillovers.
2.1 The methodological issues
Empirical results from papers find no robust causality between financial in-
tegration and economic growth. One reason is the issue of reverse causality.
The countries that have opened their financial markets are also highly devel-
oped (Edison et al., 2002). Another reason is endogeneity issues because it is
complex to account for all determinants of growth (Rey, 2013). Furthermore,
a recent theoretical study by Coeurdacier et al. (2020) finds that the effects
of financial integration are heterogeneous. The effects are heterogeneous since
they depend on how large the economies are and their level of capital before
they integrate their financial markets with other economies (Coeurdacier et al.,
2020). This acknowledgment is vital, as most empirical papers focus on average
rather than the effects for the individual economies. Finally, economists use
many different methods of measuring financial integration. As a result of the
methodological challenges, recent papers on financial integration focus on the
US monetary policy spillovers.
2.2 The Global Financial Cycle
Financial integration has changed the dynamics of the international financial
markets by making them more interdependent. For instance, introducing the
euro has increased the interdependence between the euro-area countries and the
US (Lane, 2008). This interdependence on the financial markets has given rise to
a modern phenomenon known as the ’Global Financial Cycle’ (Rey, 2013). The
’Global Financial Cycle’ refers to the contemporaneous movement of prices for
financial assets, banks’ leverage, global domestic credit, and cross-border credit
flows (Rey, 2013). It also involves a synchronization of global risk aversion and
uncertainty, often measured by the VIX (Forbes & Warnock, 2012). A ’global
factor’ triggers these co-movements (Rey, 2013). However, what exactly drives
this global factor? US monetary policy is the answer, as it is the center economy
in the financial markets. For example, the dollar is the anchor currency, the
global economy’s primary reserve currency (Rey, 2013). Kalemli- ¨Ozcan (2019)
also finds strong evidence that US monetary policy affects global risk, which
propagates to domestic credit costs. Moreover, they find that the spillovers from
US monetary policy are larger in emerging markets (Kalemli- ¨Ozcan, 2019).
2.3 The international transmission channels of monetary
policy
Two main channels of monetary policy transmit to the global financial cycle:
the risk-taking channel (Borio & Zhu, 2008) and the credit channel (Bernanke &
Gertler, 1989). Before the Global Financial Crisis, central bankers overlooked
how short-term interest rates affect banks’ financial intermediation (Borio &
Zhu, 2012). However, Borio and Zhu (2008) found a new monetary policy
transmission channel. The monetary policy from the US propagates to the VIX
6
-- 6 of 43 --
via the risk-taking channel, which impacts the financial markets more directly
than the other channels. The risk-taking channel of monetary policy operates
in this cycle: A US monetary policy loosening will make it cheaper for foreign
banks to fund their investment and lending using the dollar. Decreased costs
for the banks impact their incentives, making them less risk-averse. Their in-
centives change as they borrow given the short-term interest rate, whereas they
lend given the long-term interest rate. So, a lower short-term rate will make
the yield curve more steep. As a result of the decreased risk aversion, interna-
tional banks increase their leverage by financing their assets to a greater extent
via debt rather than equity. The currencies in the economies the capital flows
into will appreciate because of higher demand for the US dollar. The appreci-
ated currencies strengthen the domestic borrowers’ balance sheets in the capital
flow-recipient economies, decreasing the risk for international banks’ loans. Ul-
timately, this will create a cycle where the leverage of the international banks
increases again (Borio & Zhu, 2012).
Empirical evidence on the matter also confirms these channels. The seminal
paper from Rey (2013) finds that the US monetary policy spillovers transmit to
the global economy via cross-border credit and leverage. Bruno and Shin (2012)
also find evidence for the risk-taking channel, as a FED loosening will increase
banking sector capital flows because of the bank’s leverage. Results from a
global VAR also find that the two channels are the same for unconventional
US monetary policy (Georgiadis, 2015). Finally, US monetary policy spillovers
remain significant after the Global Financial Crisis (Miranda-Agrippino & Rey,
2020).
2.4 Optimal monetary policy in an interconnected world
The international transmission channels of US monetary policy led to a sudden
shift from the impossible trinity. Instead, an ’irreconcilable duo’ arises where
economies with floating and fixed exchange rates face a dilemma: they must use
capital controls or macroprudential policies to implement independent monetary
policy (Rey, 2013). Macroprudential policies are policies that aim to create fi-
nancial stability in an economy (Milne, 2009). Such policies are necessary for
central bankers to implement optimal monetary policy, where they can stabilize
the domestic output gap and inflation. If the non-center economies do not im-
plement the policies, all economies except the US will, in principle, have fixed
exchange rate regimes.
Implementing financial integration has both positive and negative effects. Fi-
nancial integration poses an economic trade-off between a faster transition to a
steady state and financial stability (Georgiadis, 2015). This trade-off is also why
some economists argue that financial integration is only efficient when combined
with government regulation. Otherwise, banks will become too leveraged be-
cause of profitable transactions. A leverage that is too high can cause systemic
risk, like during the Global Financial Crisis (Stiglitz, 2010). Central banks,
including the European Central Bank, have implemented macroprudential poli-
cies to lower banks’ leverage and excessive risk-taking to prevent these systemic
risks.
7
-- 7 of 43 --
3 Description of Data
This section describes the collected data and the calculated variables (see Ap-
pendix A for a technical understanding). The seven variables in my model
are the same as Rey (2013) uses in her seminal paper. They are given by GDP,
GDPDEF, CREDIT, INFLOW, EULEV, EFFR, and the VIX (Rey, 2013). The
variables are essential in the dynamics of the global financial markets, and some
are predictors of financial crises (Rey, 2013). My sample is more recent, span-
ning from 2001Q4 to 2023Q3. I collect data for GDP, GDPDEF, EFFR, and
the VIX from the Federal Reserve of Saint Louis. Moreover, I collect data for
CREDIT, INFLOW, and EULEV from IFS. Three of the seven variables are
relevant: the European banking sector leverage (EULEV), the effective federal
funds rate (EFFR), and the CBOE volatility index (VIX). Look at Appendix A
for a description of the other variables, calculation, and citation for all variables.
3.1 The Effective Federal Funds Rate (EFFR)
The US monetary policy variable in my recursive VAR is the effective federal
funds rate (EFFR). The Federal Reserve calculates the effective federal funds
rate as the median of the effective overnight rate at which banks in the US
borrow reserves on the interbank market. I use the effective federal funds rate,
as it is a short-term rate, which implies that it is affected more directly by
monetary policy (Bruno & Shin, 2012). If I used a long-term rate instead, the
changes would depend more on other factors than monetary policy. I collect the
effective federal funds rate as monthly data, which I aggregate into quarterly
data by taking the quarterly average.
3.2 CBOE Volatility Index (VIX)
I use the CBOE Volatility Index (VIX) to measure global risk in my recursive
VAR. The VIX measures the expected forward-looking volatility of the stock
market. Generally, a lower VIX will cause an increase in the prices of stocks.
Chicago Board Options Exchange (CBOE) calculates it by the options prices in
the S&P500 index. I use the daily calculated VIX (VIXCLS), the closing value.
I aggregate the VIX into quarterly data by taking the average for each quarter.
This definition contrasts Rey as she uses quarterly data provided by CBOE.
I take the natural logarithm of the VIX to normalize the impulse response
functions. The VIX is essential in my recursive VAR, as it is synchronized with
the global financial cycle (Rey, 2013).
3.3 European Banking Sector Leverage (EULEV)
One of my variables for the global financial cycle in the recursive VAR is the
European Banking Sector Leverage (EULEV). Banking Sector Leverage is the
ratio between a banking sector’s debt relative to the sector’s capital (Rey, 2013).
A high banking sector leverage implies that the banks finance their assets using
loans rather than equity. Higher leverage can be a cause of concern, as it is
one of the indicators of instability in the financial sector (Bruno & Shin, 2012).
The focus is on the European banks, as the Euro Area is highly financially
integrated with the US (Lane, 2008). Furthermore, a high degree of financial
8
-- 8 of 43 --
development often implies a higher leverage, and the Euro Area has one of the
most developed financial markets (Georgiadis, 2015).
3.4 Descriptive statistics of the variables
I create times series plot in Figure 3.4.1 to inspect the stationarity of my vari-
ables.
Figure 3.4.1: Times series plots for the variables
The descriptive statistics for the variables can be seen in Table 3.4.1.
GDP GDPDEF CREDIT INLFOW EULEV EFFR VIX
Mean 18029.38 94.14 20.1 7071.89 1.13 1.45 2.92
Median 17479.75 93.65 20.02 7374.6 1.2 0.99 2.85
Maximum 22490.69 122.76 21.04 9710.6 1.34 5.33 4.07
Minimum 14253.57 74.79 19.5 2710.6 0.82 0.07 2.33
Std. Dev. 2245.8 12.03 0.37 1709.51 0.15 1.66 0.34
Skewness 0.27 0.44 1.37 -0.99 -0.69 1.16 0.7
Kurtosis 2.02 2.7 4.05 3.28 2.18 3.12 3.36
Observations 88 88 88 88 88 88 88
Table 3.4.1: Descriptive statistics of the variables in the recursive VAR analysis
9
-- 9 of 43 --
4 Econometric model
This section explains my recursive VAR, its importance, and its limitations
in answering my research question. The model’s econometric theory is from
Killian and L¨utkepohl’s textbook (2016). I take considerable inspiration from
Rey’s (2013) recursive VAR to analyze the spillovers from a US monetary policy
shock.
4.1 Reduced form Vector Autoregression
In order to estimate my recursive VAR, I have to first estimate a reduced form
VAR. My general reduced form VAR equation is:
yt
7×1
= A1
7×7
yt−1
7×1
+ A2
7×7
yt−2
7×1
+ · · · + Ap
7×7
yt−p
7×1
+ ut
7×1
(4.1.1)
The endogenous variables of my reduced form VAR correspond to that of Rey
(2013):
yt
7×1
=










GDPt
GDPDEFt
log (CREDITt)
INFLOWt
EULEVt
EFFRt
log (VIXt)










(4.1.2)
My model’s coefficients are in the 7 × 7 A-matrix.
A1
7×7
=










a11 a12 a13 a14 a15 a16 a17
a21 a22 a23 a24 a25 a26 a27
a31 a32 a33 a34 a35 a36 a37
a41 a42 a43 a44 a45 a46 a47
a51 a52 a53 a54 a55 a56 a57
a61 a62 a63 a64 a65 a66 a67
a71 a72 a73 a74 a75 a76 a77










(4.1.3)
The errors for my reduced form VAR are:
ut
7×1
=










uGDP
t
uGDPDEF
t
uCREDIT
t
uINFLOW
t
uEULEV
t
uEFFR
t
uVIX
t










(4.1.4)
4.2 Inference
To analyze the properties of my estimator, I conduct misspecification tests,
where I use a significance level of five percent.
10
-- 10 of 43 --
4.3 Structural Vector Autoregression
A recursive VAR is a special type of a Structural Vector Autoregression (SVAR).
SVARs are VAR models, where the shocks in the model are theoretically grounded
(Killian & L¨utkepohl, 2016). The SVAR is given by:
B0
7×7
yt
7×1
= B1
7×7
yt−1
7×1
+ B2
7×7
yt−2
7×1
+ . . . + Bp
7×7
yt−p
7×1
+ B−1
0
7×7
wt
7×1
(4.3.1)
4.4 Cholesky decomposition
The errors must be mutually uncorrelated to estimate a recursive VAR, referred
to as orthogonalization. I orthogonalize the errors, ut, using Cholesky decom-
position, ordering variables like Rey (2013). The order is a causal chain that
makes it recursive. The VAR is recursive since the variable ordered first will
only respond to shocks to the variable ordered first in the first quarter. In the
first quarter, the variable ordered second will only respond to a shock in the
variable ordered first and the variable itself. The equation for the last order
variable will consist of its lagged values and all the lower variables. The causal
chain should be grounded in theoretical considerations (Killian & L¨utkepohl,
2016). My order is GDP, GDPDEF, CREDIT, INFLOW, EULEV, EFFR, and
the VIX. For a visualization of the contemporaneous effects; see Figure B.2.
I describe the theoretical rationale based on institutional knowledge for ordering
the variables in the recursive VAR. The variable ordered first is the US GDP, a
more long-run variable that will only respond contemporaneously to shocks to
itself. The second ordered variable is the GDP Deflator because US inflation
should respond contemporaneously to US GDP. The theoretical rationale behind
this ordering is due to Okun’s law, which is the inverse relationship between
observed unemployment and GDP (Okun, 1962). So, an increase in US GDP
causes US unemployment to fall. From the fall in unemployment, salaries will
increase such that inflation increases cf. the Phillips curve (Phillips, 1958).
The variable ordered third is global domestic credit. Global domestic credit
should respond within the first quarter to US GDP, as a higher US GDP will
increase the demand for global credit, which leads to credit growth (Gillchrist
et al., 2014). Furthermore, global domestic credit should rise when there is a
positive US inflation shock. Higher US inflation will, ceteris paribus, lead to a
depreciation of the US Dollar. From this, international firms’ currency risks will
decrease, as the global reserve currency is the US dollar (Rey, 2013). Also, since
the debt is lower then banks more may be willing to lend. These relationships
are due to financial integration, where a domestic shock to a large economy such
as the US transmits to the international financial markets. The variable ordered
fourth is the cross-border credit flow.
However, the ordering of global domestic credit and cross-border credit flow
does not matter for my interpretations, as I will show in my robustness checks.
It is just an assumption that Rey (2013) uses to build the recursive VAR, and
this approach is called partial identification. This is because I am primarily
interested in the three last-ordered variables. I use the exact ordering as Rey
(2013) either way to better compare my results to hers.
The variable ordered fifth is the European Banking Sector Leverage. The lever-
age of the European banks should increase from a positive shock to cross-border
11
-- 11 of 43 --
credit flow and global domestic credit since more credit is available. The variable
ordered second-last is the effective federal funds rate such that it can respond
contemporaneously to all variables but not the VIX. The effective federal funds
rate responds to a contemporaneous shock to the leverage of European banks.
This is because the financial markets are interconnected, and thereby, leverage
might transmit to the effective federal funds rate by changing the demand for
money (Georgiadis, 2015). The variable ordered last is the VIX, which will
respond contemporaneously to shocks from all variables in the recursive VAR.
The VIX is ordered last, as the effective federal funds rate can affect global
risk by signaling the future economic situation to investors. Moreover, the VIX
responds to contemporaneous shock to the leverage of European banks via the
risk-taking channel of monetary policy (Section 2.3). With this causal chain
in the recursive VAR, it will be possible to analyze how a US monetary policy
shock propagates to the global financial cycle.
I estimate a lower-triangular Cholesky decomposition matrix for the contempo-
raneous shocks in the recursive VAR:
B0
7×7
−1 =










b11 0 0 0 0 0 0
b21 b22 0 0 0 0 0
b31 b32 b33 0 0 0 0
b41 b42 b43 b44 0 0 0
b51 b52 b53 b54 b55 0 0
b61 b62 b63 b64 b65 b66 0
b71 b72 b73 b74 b75 b76 b77










(4.4.1)
With Cholesky decomposition, the orthogonalized standard errors for my just-
identified model, becomes:
ut
7×1
= B−1
0
7×7
wt
7×1
(4.4.2)
In matrices, the orthogonalized errors are (Killian & L¨utkepohl, 2016):










uGDP
t
uGDPDEF
t
uCREDIT
t
uINFLOW
t
uEULEV
t
uEFFR
t
uVIX
t










=










b11
0 0 0 0 0 0 0
b21
0 b22
0 0 0 0 0 0
b31
0 b32
0 b33
0 0 0 0 0
b41
0 b42
0 b43
0 b44
0 0 0 0
b51
0 b52
0 b53
0 b54
0 b55
0 0 0
b61
0 b62
0 b63
0 b64
0 b65
0 b66
0 0
b71
0 b72
0 b73
0 b74
0 b75
0 b76
0 b77
0




















w1t
w2t
w3t
w4t
w5t
w6t
w7t










(4.4.3)
Equation (4.4.3) shows how the contemporaneous shocks are ordered in the
causal chain. The coefficients not on the main diagonal are the contemporaneous
responses from shocks in my causal chain, whereas the main diagonal shows
the effects of a shock on the given variable. Each coefficient, b, shows the
contemporaneous effect of a shock on the variables. The zeros indicate that the
given variable does not respond to the contemporaneous shock.
4.4.1 Advantages and limitations of the recursive VAR
I use a recursive VAR to interpret the causal short-run relationships between my
variables. If I used a reduced form VAR to analyze the short-run relationships,
12
-- 12 of 43 --
it would be hard to interpret the causal relationships since all of my variables
would respond to each other within the first quarter. Consequently, I could not
analyze the propagation of a US monetary policy shock. Furthermore, using the
recursive VAR, I can decompose the forecast error variance of the VIX (Killian
& L¨utkepohl, 2016).
Generally, macroeconomists often use recursive VARs to analyze short-run dy-
namics. However, they do pose some challenges. One of the challenges is to
analyze the sensibility of the ordering. In my recursive model, I have seven
different orders, but I cannot be sure about the precise Cholesky ordering of
the variables (Killian & L¨utkepohl, 2016). Rey (2013) bases the ordering on
assumptions from institutional knowledge, which I have argued for in Section
4.4. For my recursive VAR, there are 7! = 5040 possible orderings. However,
I will ignore this consideration for the empirical analysis and assume that the
ordering of the last-ordered variables is still correct.
4.5 Structural Impulse Response Functions
I estimate the structural shocks based on the orthogonalized errors from equa-
tion (4.4.3). There are seven shocks in my recursive VAR, as I assume that the
number of shocks equals the number of variables (Killian & L¨utkepohl, 2016).
The number of structural impulse response functions in my model is 72 = 49.
The x-axis is denoted by the quarters i = 0,1,2,...,20. From the responses and
shocks, I estimate the structural impulse response functions as follows:
∂yt
∂w′
t−i
= ∂yt+i
∂w′
t
= Θi, i = 0,1,2,...,20 (4.5.1)
Since my recursive VAR is linear, the opposite response will occur if I analyze a
negative structural shock instead of a positive one (Killian & L¨utkepohl, 2016).
I will utilize this property in my empirical analysis of the propagation of a US
monetary policy loosening.
4.5.1 Bootstrap estimation of confidence intervals
I estimate the confidence intervals for the responses in my impulse response
functions by bootstrapping. Bootstrapping is a method used to approximate a
sampling distribution based on the observed data. I use 1000 bootstrap replica-
tions, ˆθ = (θ∗
1 , θ∗
2 , . . . , θ∗
1000). Here, the confidence interval of 95 percent will be
given by: [θ∗
25, θ∗
975]. Ultimately, when using bootstrapping, I want to approxi-
mate the distribution of the sample by a bootstrap distribution, ˆθB − ˆθ (Singh
& Xie, 2010). Furthermore, I use Hall’s (1992) percentile, where the ”Edge-
worth expansion” term is added. This extra term accounts for the skewness of
the data, thereby increasing the accuracy. I chose this method as an assump-
tion of asymptotic confidence intervals because I do not know the asymptotic
distribution of the data.
13
-- 13 of 43 --
5 Empirical results
In this section, I find the empirical results for my research question by estimating
the impulse response functions from the recursive VAR.
5.1 Unit root analysis
I begin by examining the stationarity of the variables included in the recursive
VAR. This procedure is essential because stationarity of the VAR is required for
the impulse response functions (Killian & L¨utkepohl, 2016). Based on graphical
inspection, it could be the case that my variables are trend-stationary. There-
fore, I include a time trend in the reduced-form VAR to eliminate the trend
effects. Also, by removing the variables’ common trend components, I decrease
their correlation. By decreasing their correlation, I avoid multicollinearity and
ensure more accurate estimates (Table B.8).
I conduct Augmented Dickey-Fuller tests to test for the presence of unit roots,
and thereby non-stationarity, in the variables; see Table B.1. I impose a maxi-
mum of four lags in the test, as my data are quarterly, and the criterion used is
the Schwarz info criterion; see Table B.3. All the tests conducted on the level
variable with an intercept and a time trend do not lead to a rejection of the null
hypothesis of a unit root.
Usually, I make all of my variables stationary by taking their differences to
ensure my estimates are consistent and avoid spurious correlations. However,
in my recursive VAR, I ignore the non-stationary of my variables if and only
if my reduced form VAR is stable. This is first and foremost because I am
only interested in the short-run dynamics. Second, if I take the differences of
first order, then there is a risk of my estimates becoming inconsistent because
of white noise (Georgiadis, 2015). I would lose information, and it would be
harder to interpret the short-run dynamics from the impulse response functions.
Furthermore, the variables would adjust to their equilibria too quickly compared
to Rey’s (2013) impulse response functions.
5.2 Estimation of the reduced-form VAR
I estimate the reduced form VAR after describing my empirical considerations
about the stationarity of my variables. The suggested lag length is at two lags
based on the lag length criteria (LR, FPE, AIC, SC, and HQ) (Figure B.2).
This is because LR, FPE, and AIC are lowest at two lags, while SC and HQ are
lowest at one lag. Therefore, my preferred reduced form VAR is VAR(2) since
it had lower information criteria than VAR(1). Adding more lags also increases
the risk of instability in my impulse response functions (Bruno-Shin, 2012).
I create a graph for the inverse roots of the Autoregressive characteristic poly-
nomial to ensure the stationarity and stability of my reduced form VAR (see
Figure B.1). All inverse roots are inside the unit circle in the complex plane;
therefore, my reduced form VAR is stable, and the VAR residuals are stationary.
This result is no coincidence, as it suggests some co-integrating relationships be-
tween the variables in my reduced-form VAR rather than spurious relationships.
14
-- 14 of 43 --
I conduct a Johansen unrestricted cointegration rank test (Table B.7). Based
on the trace tests, I find five co-integrating equations in my reduced-form VAR.
5.2.1 Misspecification tests
I conduct misspecification tests to investigate the properties of my variables and
VAR. First, I test for autocorrelation using a Lagrange Multiplier test and find
that my residuals are not serially correlated (Table B.3). The next tests are
normality tests with Cholesky of covariance as the orthogonalization method.
The residuals in US GDP and Effective Federal Funds Rate are non-Gaussian
distributed. Next, I conduct heteroskedasticity tests with no cross terms. The
residuals in US GDP, US GDP Deflator, CREDIT, Effective Federal Funds
Rate, and my model suffer from heteroskedasticity. The non-gaussian and het-
eroskedastic residuals may result in biased and inefficient estimates, and a bet-
ter estimator will exist. Inefficiency occurs because I estimate the reduced-form
VAR(2) using Quasi-Maximum Likelihood.
Furthermore, the effective federal funds rate shows signs of ARCH effects (Table
B.6). The ARCH effects affect my model, as I need to estimate it using a het-
eroskedasticity robust estimator such as the MLE or QMLE. Finally, I conduct
a RESET test for the correct functional form. With a test statistic of 3.58, my
variables might have a misspecified functional form. I want to keep the failed
RESET test in mind, but I do not transform my variables further, as I want my
results to be comparable to Rey’s (2013) results.
5.3 The structural impulse response functions
I use Cholesky decomposition on the variables in this order: US GDP, US GDP
Deflator, Global Domestic Credit, Global Inflow, and European Banking Sec-
tor Leverage (Rey, 2013). The ordering has been chosen based on institutional
knowledge, which I account for in Section 4.4
Furthermore, I use the degrees of freedom adjusted Cholesky ordering with a one
standard deviation shock (Table 3.4.1). The standard errors are estimated as
bootstrap errors using Hall’s percentile. The errors are bootstrap since I reject
normality in my residuals and do not know the asymptotic distribution. Using
bootstrap errors, I ensure that the errors are robust. In addition, the percentile
method is the Hall’s percentile since it is more robust to skewed data than the
standard percentile (Hall, 1992). The 95 percent confidence interval is computed
using 1000 single bootstrap replications. The total number of quarters is 20,
which makes it easier to compare to Rey (2013) in section 7. I have included the
essential impulse response functions in Figures 5.4.1 to 5.4.5, while the other
results are in Figure B.3.
15
-- 15 of 43 --
Figure 5.4.1: Response of VIX to a shock in the Effective Federal Funds Rate
Figure 5.4.2: Response of global
domestic credit to a shock in the VIX
Figure 5.4.3: Response of cross-border
credit flow to a shock in the VIX
Figure 5.4.4: Response of European
Banking Sector Leverage to a shock in
the VIX
Figure 5.4.5: Response of Effective
Federal Funds Rate to a shock in the
VIX
16
-- 16 of 43 --
5.4 Empirical findings
In this subsection, I list my impulse response functions’ most important signif-
icant results. Impulse response functions are significant when the confidence
interval does not contain zero. From the impulse response function in Figure
5.4.1, I find that the VIX initially will decrease until the five quarters from a
1.66 bonus point shock (Table 3.4.1) in the effective federal funds rate. Here-
after, the VIX will increase from 10 quarters. From a positive VIX shock, the
leverage of European banks will decrease until ten quarters, as seen in Figure
??. A positive shock to the VIX increases global domestic credit until 19 quar-
ters, as seen in Figure ??. A negative shock to the VIX results in a decrease in
the cross-border credit inflow until eight quarters.
The following results can be found in the impulse response functions in the
appendix (Figure B.3). A positive shock to the VIX will increase the effective
federal funds rate after 14 quarters. The leverage of the European banks will
decrease in quarters 12 to 16 after a US monetary policy shock. A positive
shock to European banking sector leverage will decrease the global domestic
credit until 19 quarters. A positive shock to the effective federal funds rate
will decrease European banks’ leverage in quarters 12 to 15. A positive shock
to the effective federal funds rate increases the global domestic credit after
13 quarters. A positive shock to European banking sector leverage decreases
the VIX until ten quarters. A positive shock to the European banking sector
leverage decreases global domestic credit. A positive shock to the VIX will
cause the US GDP Deflator to increase after five quarters. A positive shock to
CREDIT will decrease VIX until five quarters and increase after 15 quarters.
5.5 The impact of a US monetary policy shock on the VIX
To further analyze the impact of the effective federal funds rate on the VIX, I
decompose the forecast error variance for the VIX into shocks of the variables
using my recursive VAR in Figure 5.6.1 (Killian & L¨utkepohl, 2016). I estimate
the standard errors using 1000 Monte Carlo repetitions. For over 20 quarters,
the impact of the effective federal funds rate shocks on the variance in VIX
is, on average, approximately 12 percent. However, the impact is insignificant
since the confidence interval contains zero.
17
-- 17 of 43 --
Figure 5.6.1: Variance decomposition of VIX due to EFFR shocks
18
-- 18 of 43 --
6 Robustness
I perform the same robustness checks as Rey (2013) to check if my empirical
results are robust and consistent. First, I check if the results are robust in a
different time sample by selecting the pre-COVID-19 period, 2001Q4-2019Q4
(Figure C.1). I still get the same results, but cross-border credit flow now re-
sponds negatively to a positive shock in the VIX, as in Rey’s (2013) paper. The
impact of the effective federal funds rate on the variance in the VIX is on aver-
age 8 percent but also insignificant in the pre-COVID-19 sample (Figure C.7).
Next, I check if my model is over-fitted since a too complex model will have
low bias but high variance. I do this by removing the financial variables global
domestic credit, European banking sector leverage, and cross-border credit flow
(Figure C.2). In the four variable VAR in the pre-COVID-19 period, the im-
pact is now approximately 18 percent but still insignificant. I also do robustness
checks for the lag structure in Figure C.3, where I look at my impulse response
functions with one lag. Still, I get the same results with one lag. Finally, ex-
amining a period similar to Rey (2013) is interesting. In the last robustness
check, I estimate the impulse response functions for the period 2001Q4-2012Q4
(Figure C.4). Here, I find that a shock to the VIX will decrease global domestic
credit, and a VIX shock will decrease cross-border credit flow, consistent with
Rey (2013).
All in all, the dynamics between European banking sector leverage, effective
federal funds rate, and the VIX are robust. On the other hand, the dynamics
regarding global domestic credit and cross-border credit flow are not robust.
19
-- 19 of 43 --
7 Discussion
In this section, I analyze how a US monetary policy shock will propagate to the
global financial cycle, relate the results to the literature, and provide criticisms
of my recursive VAR. In parts of my discussion, I interpret the different results
based on my assessments since the research in my period is limited.
7.1 The propagation of a US monetary policy shock
The effects of the US monetary policy spillover on the global financial cycle
persist. I analyze how a US monetary policy shock will propagate to the global
financial cycle in this subsection. Initially, a US monetary policy loosening in-
creases global risk, inconsistent with Rey (2013). Miranda-Agrippino and Rey
(2020) analyze the US monetary policy spillovers after the Global Financial Cri-
sis until 2019 and find a similar result. The mechanism behind this result is
an information effect: A combination of US monetary policy loosening and the
FED communicating pessimistic news about the projections for the economy
will initially increase the VIX. During the COVID-19 pandemic, US monetary
policy loosened, and a bad economic outlook also occurred (Condon, 2020).
After nine quarters, the global risk decreases by improving the confidence of
global investors (Forbes & Warnock, 2012). The lower global risk propagates
to the European banks by making them less risk-averse, resulting in the banks
acquiring more debt. As a result of this, their leverage increases. Furthermore,
the US monetary policy loosening also propagates to lower costs for European
banks after 12 quarters (Bruno & Shin, 2012). Lower costs for banks change
their risk attitudes because they want to maintain the same risk of absorbing
losses (Value-at-risk) (Adrian & Shin, 2010). There is heterogeneity between the
risk attitudes of the European banks, such that primarily, the more risk-taking
European banks will higher their leverage even more (Miranda-Agrippino & Rey
2020). The increased leverage will lead to even lower global risk. Lower global
risk further loosens the US monetary policy, and the responses reoccur.
All in all, a feedback cycle exists between US monetary loosening, leverage of
European banks, and the VIX in the impulse response functions, consistent with
Rey’s (2013) paper and the international risk-taking channel of monetary pol-
icy. However, increased VIX from higher cross-border credit flow in my recursive
VAR are inconsistent with the cycle from the risk-taking channel of monetary
policy (Bruno & Shin, 2012).
My findings from Section 5.4 show that in my recursive VAR, the impact of the
effective federal funds rate on the variance of the VIX is on average 12 percent.
Compared to Rey (2013), this impact is significantly higher, as she finds an
impact of only 4 percent.
7.2 Is the VIX dead?
Some of my empirical findings differ from Rey (2013). In my recursive VAR, a
positive shock to the VIX increases the global domestic credit until 19 quarters
20
-- 20 of 43 --
and cross-border credit flow until seven quarters, whereas Rey finds a nega-
tive response. My results contradict the existing empirical literature. Here
is why: volatility shocks widen credit spreads, meaning the costs for a firm’s
borrowing increase. Firms respond by a ”wait-and-see”-strategy, where they
reduce investments in new capital and instead focus on paying off their debt.
Firms implement the strategy because they are often risk-averse (Sung, 2005)
and want to avoid bankruptcy. A positive volatility shock ultimately results in
lower credit demand (Gilchrist et al., 2014). In addition, firms lower their de-
mand for credit, as in periods with positive volatility shocks, it is often harder to
insure against losses, as evidence from the Global Financial Crisis shows (Arel-
lano et al., 2016). In the period 2001Q4-2012Q4, I find that these mechanisms
hold, consistent with Rey (2013) (Section 6).
What could explain this positive relationship in the COVID-19 period? More
regulation and macroprudential policies might be the answer. Central bankers
have implemented these policies since the Global Financial Crisis to prevent
excessive risk-taking in the risk-taking channel of monetary policy (Saft, 2016).
Such policies include the Basel III reforms, which implemented capital buffers
and stress tests (Gale et al., 2011). Georgiadis (2015) analyzes the determinants
of US monetary policy spillovers, where he finds that financial development in
the domestic economy is a significant determinant. Regulation might increase
financial development, as efficient policies decrease the risks of financial crises.
As a result of the regulation, the VIX, global domestic credit, and cross-border
credit flow have all been low in the post-2009 period. Avdjiev et al. (2017)
find that the dollar might better determine cross-border credit flows during the
post-Global Financial Crisis period. Since 2014, the VIX has been insignificant
in determining the 3-month cross-currency basis when they add the dollar to
the regression. In their regression, the dollar has a negative effect. So, when
the dollar appreciates, the cross-currency basis will fall, indicating a currency
mismatch on the balance sheets of international banks. This currency mismatch
causes international banks to deleverage because of higher currency risk, and
the banks’ risk-taking will fall (Avdjiev et al., 2017).
Some investors have also begun criticizing the VIX as a measure of global risk
after the Global Financial Crisis. They argue that the VIX is too low, especially
after the Russian Invasion of Ukraine. The reason for a lower-than-normal VIX
is the increase in the demand for options that expire within the same day one
invests in them (0DTE options). My VIXCLS measures the options that ex-
pire within a month, so it does not account for 0DTE options. CBOE is now
calculating the VIX1D to counter the increased trading, which they calculate
multiple times daily (Cruz, 2023).
7.3 The size of the US monetary policy spillovers
The response of the VIX to a US monetary policy shock in my impulse response
function is challenging to compare to Rey (2013) in percentage points. Rey
normalizes her monetary policy shock to 25 bonus points, whereas mine is only
1.66. Therefore, I calculate the scaled responses to a 25 bonus point shock to
the effective federal funds rate in Table B.9. The response for the VIX from a
21
-- 21 of 43 --
shock to the effective federal funds rate is not as large as Rey’s (2013). Also,
changes in VIX still lead European banks to take on more leverage, but to a
lesser extent compared to Rey (2013). These two results are likely because of
more regulation.
7.4 Criticisms of my analysis
A challenge for my model is that none of the variables account for the uncon-
ventional monetary policies central banks implemented during the COVID-19
pandemic. However, empirical studies show that such analyses are complex
(Miranda-Aggripino & Rey, 2020). Also, it is hard to compare my responses for
US GDP and cross-border credit flow directly to Rey (2013), as she normalizes
these responses to percentage points.
There is also a potential problem regarding my confidence intervals in the im-
pulse response functions. The confidence intervals could be inaccurate because
of skewness in some of my variables; see Figure C.5, as I use percentile boot-
strapping (Rousselet et al., 2021). Hence, if I had more time to familiarize myself
with advanced bootstrapping methods, then I would try the Bias-Corrected and
accelerated bootstrap. This is because BCa bootstrap often estimate more the
confidence interval more precise (DiCiccio & Efron, 1996).
My two average-aggregated variables, the effective federal funds rate and the
VIX, also likely smooth out the short-run fluctuations, which could withhold
important information. Finally, my sample has only 88 observations, with the
earliest observations being in 2001Q4. Finally, factors other than US mone-
tary policy might affect effective federal funds, such as the demand for money
(Georgiadis, 2015).
22
-- 22 of 43 --
8 Conclusion
My thesis aimed to discover if there are still spillovers from US monetary policy.
There are still spillovers from US monetary policy. However, the magnitude
of the spillovers is lower in the COVID-19 period compared to Rey’s (2013)
period. A US monetary policy loosening will propagate to the global econ-
omy by decreasing the global risk and increasing the leverage of the European
banks. Moreover, the higher leverage of the European banks will further de-
crease the VIX, which again increases the leverage. Although European banks
have deleveraged since the Global Financial Crisis, the central banks should
still monitor the leverage. My robustness checks show that my results cannot
be generalized to different periods. However, my thesis might provide worthful
information about how the US monetary policy propagates to the global econ-
omy during global lockdowns like the COVID-19 pandemic. This thesis also
contributes to the literature on why the COVID-19 pandemic did not become
another global financial crisis. This might be because of higher cross-border
credit flows, not further lowering the VIX and because of lower VIX not in-
creasing global domestic credit and cross-border credit flows (the cycle in the
risk-taking channel) due to regulation and macroprudential policies (Saft, 2016).
Examining how unconventional US monetary policy propagates to the global fi-
nancial cycle via leverage, credit growth, and cross-border credit flows in the
COVID-19 period could be interesting. Finally, future research could analyze if
the dollar is a better measurement for global risk than the VIX and check if the
dynamics might change (Avdjiev et al., 2017).
23
-- 23 of 43 --
References
Arellano, C., Bai, Y., & Kehoe, P. (2016). ”Financial Frictions and Fluc-
tuations in Volatility”. Journal of Political Economy, 127: pp. 2049-2103.
Adrian, T. & Shin, H. S. (2010). ”Liquidity and leverage”, Journal of Fi-
nancial Intermediation.
Avdjiev, S., Du, W., Koch, C., and Shin, H. S. (2017). ”The dollar, bank
leverage and the deviation from covered interest parity”, BIS Working Papers,
Bank for International Settlements.
Bruno, V. and Shin, H. S. (2008), ”Capital regulation, risk-taking and mon-
etary policy: a missing link in the transmission mechanism?”, BIS Working
Papers No 268, Bank for International Settlements, Monetary and Economic
Department.
Bruno, V. and Shin, H. S. (2012), “Capital Flows and the Risk-Taking
Channel of Monetary Policy”, BIS Working Papers No 400, Bank for Interna-
tional Settlements, Monetary and Economic Department.
Cetorelli, N. and Goldberg, L. S. (2012), “Banking Globalization and Mon-
etary Transmission”, Journal of Finance, 67(5): pp. 1811—1843.
Condon, C. (2020, May), ”Fed’s Daly Sees Negative 2020, Slow Rebound for
U.S. Economy”, Bloomberg.
Coeurdacier, N., Rey, H., and Winant, P. (2020), ”Financial integration
and growth in a risky world”, Journal of Monetary Economics, 112: pp. 1-21.
Cruz, I. D. (2023, April), ”Say Goodbye to the VIX: New Index to Reflect
Market Volatility More Accurately”, Investing.com, Seen 30/05-2024.
DiCiccio, T. and Efron, B. (1996), ”Bootstrap confidence intervals”, Statis-
tical Science, 11(3): pp. 189-228.
Edison, H. J., Levine, R., Ricci, L., Sløk, T. (2002). ”International fi-
nancial integration and economic growth”, Journal of International Money and
Finance, 21(6): pp. 749-776.
Forbes, K. J. and Warnock, F. E. (2012), ”Capital flow waves: Surges,
stops, flight, and retrenchment”, Journal of International Economics, 88(2):
pp. 235-251.
Gale D., Repullo, R., and Smets, F, International Journal of Central Bank-
ing
Georgiadis, G. (2015), ”Determinants of global spillovers from US monetary
policy”, European Central Bank, Working Paper 1854.
24
-- 24 of 43 --
Gilchrist, S., Sim, J. W., and Zakrajˇsek, E (2014), ”Uncertainty, Financial
Frictions, and Investment Dynamics”, National Bureau of Economic Research.
Hall, P. G. (1992). ”The Bootstrap and Edgeworth Expansion”, Springer Se-
ries in Statistics.
Killian, L. and L¨utkepohl, H. (2017), ”Structural Vector Autoregressive
Analysis”, Cambridge University Press.
Kalemli- ¨	Ozcan, S. (2019), ”US monetary policy and international risk spillovers”,
Working paper, National Bureau of Economic Research.
Lane, P. R. (2008), ”EMU and Financial Integration”, IIIS, Trinity College
and CEPR.
Milne, Alistair (2009), ”Macroprudential policy: what can it achieve?”, Ox-
ford Review of Economic Policy, 25(4): pp. 608-629.
Miranda-Agrippino, S. and Rey, H. (2020), ”The global financial cycle af-
ter Lehman”, AEA PAPERS AND PROCEEDINGS, 110: pp. 523-28.
Okun, A. M. (1962), ”Potential GNP: Its Measurement and Significance.”,
Proceedings of the Business and Economic Statistics Section of the American
Statistical Association, 1962, pp. 89-104.
Phillips, A. W. (1958), ”The Relation Between Unemployment and the Rate
of Change of Money Wage Rates in the United Kingdom”, 1861–19571. Eco-
nomica, 25(100): pp. 283–299.
Rey, H (2013), ”Dilemma Not Trilemma: The Global Financial Cycle and
Monetary Policy Independence”, Working paper 21162, National Bureau of Eco-
nomic Research.
Rousselet, G. A., Pernet, C. R., and Wilcox, R. R. (2021), ”The Per-
centile Bootstrap: A Primer With Step-by-Step Instructions in R”, Advances
in Methods and Practices in Psychological Science, 4(1).
Saft, J. (2016, November), ”Ding-dong the VIX is dead (but risk is rising):
James Saft”, Reuters.com, Seen 01/05-2024.
Singh, K. and Xie, M. (2010), ”Bootstrap Method” International Encyclo-
pedia of Education, 3: pp. 46-51.
Stiglitz, J. (2010), ”Risk and Global Economic Architecture: Why Full Finan-
cial Integration May Be Undesirable”, American Economic Review: Papers &
Proceeding, 100: pp. 388–392.
Sung, J. (2005), ”Optimal Contracts Under Adverse Selection and Moral Haz-
ard: A Continuous-Time Approach”. Review of Financial Studies, 18: pp.
25
-- 25 of 43 --
1021-1073.
26
-- 26 of 43 --
Appendix A
This appendix explains the data and variables used in the empirical analysis in
the recursive VAR. I describe the technical information about the collection and
transformation of the seven variables. All my data is collected quarterly from
2001Q4 to 2023Q3.
Description
GDP Real US GDP
GDPDEF US GDP Deflator, 2017=100
CREDIT Global Domestic Credit
INFLOW Cross-border credit flow
EULEV European Banking Sector Leverage
EFFR Effective Federal Funds Rate
VIX CBOE Volatility Index
Table A.1: Description of my variables
US GDP (GDP)
The US GDP-variable (GDP) is the Real Gross Domestic Product of the United
States, and the unit is billions of US Dollars, which are chained to the year 2017.
Moreover, it is a seasonally adjusted annual rate.
Citation: I retrieve the data from the Federal Reserve Bank of St. Louis
(FRED) (Link: https://fred.stlouisfed.org/series/GDP), collected February 6th,
2024. The FRED collected it from the US Bureau of Economic Analysis.
US GDP Deflator (GDPDEF)
The US GDP Deflator (GDPDEF) is the implicit price deflator for the United
States. The US GDP Deflator is also adjusted for seasonality. The base year is
2017, where the index is equal to 100.
Citation: US Bureau of Economic Analysis, Gross Domestic Product: Im-
plicit Price Deflator [GDPDEF], I retrieved the data from the Federal Reserve
Bank of St. Louis (FRED) (Link: https://fred.stlouisfed.org/series/GDPDEF),
collected February 10th 2024. The FRED collected it from the US Bureau of
Economic Analysis.
Global Domestic Credit (CREDIT)
Global domestic credit (CREDIT) is one of my variables for the global financial
cycle. I first calculate the domestic credit for the individual countries as the
total domestic claims in the Depository Corporations, except for the Central
Bank. I calculate the domestic claims as Claims on the Private Sector, Pub-
lic Non-Financial Corporations, other Financial Corporations, and Net Claims
on Central or General Government (Rey, 2013). I then calculate the Global
27
-- 27 of 43 --
Domestic variables as follows:
CREDIT =
70	X
i=1
Domestic Crediti (A.1)
I then take the natural logarithm of the global domestic credit to normalize it
into credit growth.
Citation: I have received the data on the CREDIT-variable from: Other Depos-
itory Corporation Survey and Deposit Money Banks Survey; Monetary Statis-
tics; IFS, (Link: https://data.imf.org/regular.aspx?key=63243614). The data
is collected in the national currencies of the given countries.
Countries included in the Global Domestic Credit variable
The collected data is the original data in national currencies, where I exclude
aggregate measures such as currency areas.
The list of countries becomes: Albania, Algeria, Angola, Argentina, Aus-
tralia, Belize, Benin, Bolivia, Bosnia and Herzegovina, Botswana, Brazil, Bul-
garia, Burkina Faso, Cabo Verde, Colombia, Cˆote d’Ivoire, Czechia, Denmark,
Dominican Republic, Arab Republic of Egypt, Kingdom of Eswatini, Repub-
lic of Fiji, Georgia, Guatemala, Guinea-Bissau, Honduras, Hungary, Iceland,
Indonesia, Israel, Jamaica, Japan, Jordan, Republic of Kazakhstan, Kenya,
(South) Korea, Malaysia, Mali, Mexico, Republic of Moldova, Morocco, Re-
public of Mozambique, Nambia, New Zealand, Nicaragua, Niger, Republic of
North Macedonia, Norway, Pakistan, Panama, Paraguay, Philippines, Repub-
lic of Poland, Romania, Rwanda, Senegal, Republic of Serbia, Sierra Leone,
Solomon Islands, South Africa, Republic of South Sudan, Sweden, United Re-
public of Tanzania, Thailand, Trinidad and Tobago, T¨urkyie, Uganda, Ukraine,
Uruguay, Vanuatu, and Zambia.
Citation: I retrieved the data from the IMF website; Other Depository Cor-
poration Survey and Deposit Money Banks Survey; Monetary Statistics; IFS
(Link: https://data.imf.org/regular.aspx?key=63243614), collected 14th Febru-
ary 2024.
Cross-border credit flow (INFLOW)
Another variable for the global financial cycle is cross-border credit flow (IN-
FLOW), which is the net amount of credit flowing into an economy. The variable
aggregates credit flow for a total of 54 countries.
Cross-border credit flow =
54	X
i=1
Direct Cross-Border Credit54 (A.2)
Where Direct Cross-Border Credit for the individual country is defined as (Rey,
2013):
Direct Cross-Border Credit = Claims − Liabilities (A.3)
28
-- 28 of 43 --
Countries included in the cross-border credit flow variable
I select the same sample countries in the global credit inflow panel variable as in
Rey’s (2013) paper. However, since Serbia is no longer a BIS-reporting country,
I choose Albania as an alternative for Serbia because of their similar economies.
Also, Czechia, T¨urkyie, and Hong Kong SAR have changed their names since
2013.
My list, therefore, is: Albania, Argentina, Austria, Belarus, Belgium, Bo-
livia, Brazil, Bulgaria, Canada, Chile, Colombia, Costa Rica, Croatia, Cyprus,
Czechia, Denmark, Ecuador, Finland, France, Germany, Greece, Hong Kong
SAR, Hungary, Iceland, Indonesia, Ireland, Italy, Japan, (South) Korea, Latvia,
Lithuania, Luxembourg, Malaysia, Malta, Mexico, Netherlands, New Zealand,
Norway, Poland, Portugal, Romania, Russia, Slovakia, Slovenia, South Africa,
Spain, Sweden, Switzerland, Thailand, Turkey, United Kingdom and United
States.
Citation: I retrieved the data from the BIS data portal; Table A3: Cross-border
positions, by residence and sector of counterparty (Link: https://data.bis.org/
topics/LBS/tables-and-dashboards/BIS,LBS A3,1.0), collected 20th February
2024.
European Banking Sector Leverage (EULEV)
European Banking Sector Leverage (EULEV) is the median for the 12 initial
Euro Area countries (Rey, 2013). Contrary to Rey’s (2013) EULEV variable, I
omit the Banking Sector Leverage for the United Kingdom, as Brexit happened
in 2020. The data is in the euro currency instead of the national currencies Rey
(2013) uses. The banking sector leverage for the individual country is given by:
Banking Sector Leverage = Claims on Private Sector
Transferables + Other Deposits (A.4)
Citation: I retrieved the data from the Other Depository Corporations Sur-
vey; Monetary Statistics, International Financial Statistics database; IFS (Link:
https://data.imf.org/regular.aspx?key=63243614), collected 14th February 2024.
Effective Federal Funds Rate (EFFR)
For the Effective Federal Funds Rate (EFFR), I calculate quarterly averages
based on monthly data that are not seasonally adjusted.
EFFRt = EFFRt=1 + EFFRt=2 + · · · + EFFRt=n
n (A.5)
Citation: Board of Governors of the Federal Reserve System (US), Federal
Funds Effective Rate [FEDFUNDS]. I have received the EFFR-data from the
Federal Reserve Bank of St. Louis (FRED); (Link: https://fred.stlouisfed.org/
series/FEDFUNDS), collected February 9th 2024, H.15 Selected Interest Rates.
CBOE Volatility Index (VIX)
For the VIX, I calculate quarterly averages based on daily close readings (CLS)
for the Chicago Board Options Exchange Volatility Index, which is non-seasonally
29
-- 29 of 43 --
adjusted.
VIXt = VIXt=1 + VIXt=2 + · · · + VIXt=n
n (A.6)
Citation: I retrieve the VIX-data from the FRED, Federal Reserve Bank of
St. Louis; (Link: https://fred.stlouisfed.org/series/VIXCLS), and the FRED
collected them from Chicago Board Options Exchange, I collected the data on
February 8th 2024.
30
-- 30 of 43 --
Appendix B
This is the model appendix. The software I use to estimate, is primarily
Eviews12, however, OxMetrics9 has been used to test for hetereoskedasticity
of the model and ARCH-effects for the variables.
Misspecification tests
Test statistic p-value
GDP -2.68 0.2444
GDPDEF -1.58 0.7895
CREDIT -1.32 0.8762
INFLOW -2.1 0.5334
EULEV -2.53 0.3125
EFFR -2.01 0.5835
VIX -3.46 0.0494
Table B.1: Unit root tests (Augmented Dicky-Fuller tests) for my level variables
Lag LR FPE AIC SC HQ
1 1146.56 4.2 21.29 23.11* 22.02*
2 83.41* 4* 21.23* 24.47 22.53
3 43.49 6.85 21.68 26.34 23.56
4 61.37 8.04 21.71 27.79 24.16
Table B.2: Information criteria at the different lag lengths
Lag LRE statistic Degrees of freedom p-value
1 42.34 49 0.7408
2 35.03 49 0.9345
3 46.49 49 0.5790
4 60.45 49 0.1288
Table B.3: Test for autocorrelation (Lagrange Multiplier) at the different lag
lengths
Jarque-Bera test-statistic p-value
GDP 2131.01 0.0000
GDPDEF 4.66 0.0972
CREDIT 1.9 0.3738
INFLOW 1.43 0.4875
EULEV 13.12 0.0014
EFFR 25.24 0.0000
VIX 12.04 0.0024
Joint test 2189.488 0.0000
Table B.4: Normality tests (Jarque-Ber) for the variables and VAR(2)
31
-- 31 of 43 --
Chi-sqaure p-value
GDP 3.22 0.0001
GDPDEF 4.15 0.0000
CREDIT 2.85 0.0004
INFLOW 0.74 0.8079
EULEV 1.5 0.0950
EFFR 2.64 0.0009
VIX 1.51 0.0923
Joint test 952.1415 0.0042
Table B.5: Heteroskedasticity tests (White) for the variables and my VAR(2)
Test statistic p-value
GDP 0.07 0.9897
GDPDEF 0.63 0.6449
CREDIT 0.84 0.5025
INFLOW 1.94 0.1114
EULEV 1.62 0.1768
EFFR 6.3 0.0002
VIX 0.12 0.9745
Table B.6: ARCH tests for the variables
32
-- 32 of 43 --
Figure B.1: Inverse roots of the characteristic polynomial
Eigenvalue Trace statistic Critical value p-value
0** 0.44 170.32 125.61 0.0000
1** 0.37 120.45 95.75 0.0004
2** 0.25 79.97 69.81 0.0062
3** 0.22 54.76 47.85 0.0098
4** 0.19 32.61 29.79 0.0231
5 0.12 14.32 15.49 0.0744
6 0.03 3.14 3.84 0.0762
Table B.7: Johansen cointegration rank test
33
-- 33 of 43 --
Corr
(p-value) GDP GDPDEF CREDIT INFLOW EULEV EFFR VIX
GDP 1
GDPDEF 0.97
(0.0000) 1
CREDIT 0.46
(0.0000) 0.53
(0.0000) 1
INFLOW 0.76
(0.0000) 0.77
(0.0000) 0.27
(0.0091) 1
EULEV −0.9
(0.0000)
−0.9
(0.0000)
−0.59
(0.0000)
−0.59
(−0.0000)
1
EFFR −0.02
(0.8421)
−0.04
(0.6856)
0.14
(0.1680) −0.06
(0.5418)
0.1
(0.3178) 1
VIX −0.12
(0.2580)
−0.02
(0.8000)
0.16
(0.1350) 0.06
(0.5661) −0.11
(0.2851)
−0.27
(0.0095)
1
Table B.8: Correlation matrix for the variables
34
-- 34 of 43 --
The dynamic short-run relationship
Figure B.2: Dependency graph for my ordering
The arrows in the middle indicate when the order is changing.
35
-- 35 of 43 --
Figure B.3: Impulse response functions
36
-- 36 of 43 --
Quarter Scaled response
1 -0.81
2 -0.74
3 -0.62
4 -0.56
5 -0.36
6 -0.13
7 0.09
8 0.26
9 0.39
10 0.48
11 0.55
12 0.59
13 0.61
14 0.61
15 0.59
16 0.55
17 0.51
18 0.45
19 0.39
20 0.32
Table B.9: Scaled responses for VIX for 25 bonus point increase in EFFR
37
-- 37 of 43 --
Appendix C - Robustness checks
Impulse response functions
Figure C.1: Impulse response function for the pre-COVID-19 sample
38
-- 38 of 43 --
Figure C.2: Impulse response functions in the four variable VAR
Note: The y-axis is measured as units in the response variable, and the x-axis
is quarters.
39
-- 39 of 43 --
Figure C.3: Impulse response functions for VAR(1) with seven variables
40
-- 40 of 43 --
Figure C.4: Impulse response functions for period 2001Q4-2012Q4
41
-- 41 of 43 --
Figure C.5: Histograms for the variables
Variance decompositions
Figure C.6: Variance decomposition of VIX due to EFFR shocks in pre-COVID-
19 sample
42
-- 42 of 43 --
Figure C.7: Variance decomposition of VIX due to EFFR shocks in four variable
VAR in pre-COVID-19 sample
43
-- 43 of 43 --
--- END DOCUMENT ---

--- START DOCUMENT: sample_secret.txt ---
This is a confidential document for testing the RAG system.

Secret Fact: Anton once built a functional economic model entirely in Minecraft using redstone logic gates during a university break.

Project Alpha: A hidden initiative to visualize global trade flows using WebGL. Status: Planning.
--- END DOCUMENT ---
`;
