import fs from 'fs/promises';
import path from 'path';
import pdf from 'pdf-parse/lib/pdf-parse.js';
import { createGoogleGenerativeAI } from '@ai-sdk/google';
import { generateText } from 'ai';
import dotenv from 'dotenv';
import { fileURLToPath } from 'url';

// Load env
dotenv.config();

const __dirname = path.dirname(fileURLToPath(import.meta.url));

async function main() {
    const filePath = process.argv[2];
    if (!filePath) {
        console.error("Usage: npm run curate <path-to-pdf>");
        process.exit(1);
    }

    const absolutePath = path.resolve(filePath);
    console.log(`📖 Reading PDF: ${absolutePath}...`);

    try {
        const dataBuffer = await fs.readFile(absolutePath);
        const data = await pdf(dataBuffer);
        const text = data.text.slice(0, 30000); // Limit context window

        console.log(`🧠 Analyzing content with Gemini...`);

        if (!process.env.GEMINI_API_KEY) {
            throw new Error("Missing GEMINI_API_KEY");
        }

        const google = createGoogleGenerativeAI({
            apiKey: process.env.GEMINI_API_KEY
        });

        const prompt = `
            Analyze this research paper text and extract structured metadata for a portfolio entry.
            Return ONLY valid JSON.

            Structure:
            {
                "slug": "kebab-case-title",
                "title": "Full Title",
                "subtitle": "Short descriptive subtitle",
                "date": "YYYY-MM-DD",
                "author": "Author Name",
                "executiveSummary": "2-3 sentences max.",
                "techStack": ["Tool1", "Tool2"],
                "methodology": "Brief description of methods (150 words)",
                "findings": "Key results (150 words)",
                "citationText": "APA style citation"
            }

            Text:
            ${text}
        `;

        const { text: jsonText } = await generateText({
            model: google('gemini-2.0-flash'),
            messages: [{ role: 'user', content: prompt }]
        });

        const cleanJson = jsonText.replace(/```json/g, '').replace(/```/g, '').trim();
        const metadata = JSON.parse(cleanJson);

        console.log(`✨ Extracted Metadata: ${metadata.title}`);

        // Generate Astro File
        const astroContent = `---
import ProjectDetailPage from '../../components/templates/ProjectDetailPage.astro';

const project = {
    title: "${metadata.title}",
    subtitle: "${metadata.subtitle}",
    date: "${metadata.date}",
    coverImage: "/assets/projekter/placeholder.jpg", // TODO: Add image
    heroImage: "/assets/projekter/placeholder-hero.jpg", // TODO: Add hero
    language: "en",
    authors: ["${metadata.author}"],
    tags: ${JSON.stringify(metadata.techStack)},
    techStack: ${JSON.stringify(metadata.techStack.map((t: string) => ({ name: t, icon: 'fa-solid fa-code' })))},
    
    // Abstract
    summary: "${metadata.executiveSummary}",
    executiveSummary: "${metadata.executiveSummary}",

    // Content
    methodology: \`${metadata.methodology}\`,
    findings: \`${metadata.findings}\`,
    relevance: "Automatically curated project.",
    dataTools: "Generated by Auto-Curator",

    // Downloads
    download: {
        pdfUrl: "/assets/docs/${path.basename(filePath)}",
        pdfLabel: "Download Paper"
    },

    // Citation
    citation: {
        text: "${metadata.citationText}",
        pdfUrl: "/assets/docs/${path.basename(filePath)}"
    }
};
---

<ProjectDetailPage lang="en" project={project} />
`;

        const outputPath = path.join(__dirname, `../src/pages/projects/${metadata.slug}.astro`);
        await fs.writeFile(outputPath, astroContent);

        console.log(`✅ Created: ${outputPath}`);

    } catch (err) {
        console.error("Error:", err);
    }
}

main();
