"""
Generate src/data/rolling-window-grid.json for the rolling-window simulator.

Re-estimates equation 4.1 of "Globalization and the Welfare State" on every rolling
window of every length in RANGE, and writes the coefficient and standard error on
each KOF index. The site's simulator offers whichever window lengths appear in the
output, so running this with a wider range simply enables more of the slider.

!! READ BEFORE RUNNING !!
-------------------------
The shipped JSON contains only the 10-year window, transcribed from Table 5.5 of
the paper. Running this script overwrites it — and as of commit 2218d27 of the
replication repo the two do not agree, so you would be replacing published figures
with different ones.

What was checked (2026-08-11):

  * This script's specification reproduces the paper's baseline Table 5.1 exactly
    — all four coefficients, all four t-statistics, N = 996 and R² to three
    decimals — so the data and the estimator are right.
  * The paper's rolling estimates come from a different procedure:
    src/clean/structural_breaks.py::rolling_ols_coefficients demeans the panel by
    country over the FULL 1980-2023 sample, then subsets the already-demeaned data
    to each window, with no year fixed effects and no degrees-of-freedom
    correction for the absorbed effects. That is not equation 4.1, which the paper
    says the rolling regressions estimate, and it is why its standard errors on a
    10-year window come out close to the full-sample ones.
  * Running the repo's own rolling_ols_coefficients() on its own
    data/final/master_dataset.csv still does not reproduce Table 5.5
    (overall/2023: paper 0.1831 (0.0679) vs code 0.1867 (0.0671);
     overall/2018: paper 0.1856 (0.0606) vs code 0.2776 (0.0642)).
    The published table was presumably generated by an earlier revision.

The qualitative result is unaffected either way: the coefficient rises from about
zero in windows ending before 2010 to strongly positive and significant in windows
ending 2018 or later. Only the exact numbers are in question.

Usage
-----
    pip install pandas linearmodels
    python scripts/generate-rolling-grid.py --data public/assets/data/welfare-state-panel.csv

Expected columns (as in master_dataset.csv)
-------------------------------------------
    iso3, year, sstran,
    KOFGI, KOFEcGI, KOFSoGI, KOFPoGI,
    ln_gdppc, inflation_cpi, deficit, debt, ln_population, dependency_ratio

Lags are constructed here, so supply the levels.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import pandas as pd
from linearmodels.panel import PanelOLS

INDICES = {
    "overall": "KOFGI",
    "economic": "KOFEcGI",
    "social": "KOFSoGI",
    "political": "KOFPoGI",
}

CONTROLS = ["ln_gdppc", "inflation_cpi", "deficit", "debt", "ln_population", "dependency_ratio"]

# The panel keys countries by ISO3.
ENTITY = "iso3"

# Minimum observations before an estimate is meaningful; short windows on a 32-country
# panel can otherwise produce a coefficient off a handful of degrees of freedom.
MIN_OBS = 150


def build_lags(df: pd.DataFrame) -> pd.DataFrame:
    """One-year lags of every right-hand-side variable, within country."""
    df = df.sort_values([ENTITY, "year"]).copy()
    for col in list(INDICES.values()) + CONTROLS:
        if col not in df.columns:
            raise SystemExit(f"missing expected column: {col}")
        df[f"{col}_lag1"] = df.groupby(ENTITY)[col].shift(1)
    return df


def estimate(panel: pd.DataFrame, index_col: str) -> tuple[float, float, int] | None:
    """Two-way FE with country-clustered SEs. Returns (coef, se, nobs)."""
    regressors = [f"{index_col}_lag1"] + [f"{c}_lag1" for c in CONTROLS]
    subset = panel.dropna(subset=["sstran"] + regressors)
    if len(subset) < MIN_OBS or subset.index.get_level_values(ENTITY).nunique() < 5:
        return None

    spec = f"sstran ~ 1 + {' + '.join(regressors)} + EntityEffects + TimeEffects"
    try:
        fit = PanelOLS.from_formula(spec, subset).fit(
            cov_type="clustered", cluster_entity=True
        )
    except Exception:
        return None

    key = f"{index_col}_lag1"
    return float(fit.params[key]), float(fit.std_errors[key]), int(fit.nobs)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--data", required=True, help="CSV of the OECD panel")
    ap.add_argument("--out", default="src/data/rolling-window-grid.json")
    ap.add_argument("--min-window", type=int, default=5)
    ap.add_argument("--max-window", type=int, default=20)
    args = ap.parse_args()

    df = build_lags(pd.read_csv(args.data))
    panel = df.set_index([ENTITY, "year"])
    years = sorted(df["year"].unique())

    windows: dict[str, dict[str, list[dict]]] = {}

    for length in range(args.min_window, args.max_window + 1):
        per_index: dict[str, list[dict]] = {name: [] for name in INDICES}
        for end in years:
            span = range(end - length + 1, end + 1)
            window = panel[panel.index.get_level_values("year").isin(span)]
            for name, col in INDICES.items():
                result = estimate(window, col)
                if result is None:
                    continue
                coef, se, _ = result
                per_index[name].append(
                    {"end": int(end), "coef": round(coef, 4), "se": round(se, 4)}
                )
        # Only keep a length if every index produced a usable curve.
        if all(len(v) >= 2 for v in per_index.values()):
            windows[str(length)] = per_index
            print(f"window {length:>2}y: {len(per_index['overall'])} estimates")
        else:
            print(f"window {length:>2}y: skipped (too few usable estimates)")

    if not windows:
        raise SystemExit("no window length produced usable estimates — check the input data")

    payload = {
        "_comment": (
            "Generated by scripts/generate-rolling-grid.py. Each entry is a separate "
            "estimation of eq. 4.1 on a window of `length` years ending in `end`."
        ),
        "_source": f"Generated from {Path(args.data).name}",
        "indices": {
            "overall": "Overall globalization",
            "economic": "Economic globalization",
            "social": "Social globalization",
            "political": "Political globalization",
        },
        "windows": windows,
    }

    out = Path(args.out)
    out.write_text(json.dumps(payload, indent=4) + "\n", encoding="utf-8")
    print(f"wrote {out} ({len(windows)} window lengths)")


if __name__ == "__main__":
    main()
