import fs from 'fs/promises';
import path from 'path';
import { createRequire } from "module";
const require = createRequire(import.meta.url);
const pdf = require("pdf-parse");

const documentsDir = './src/data/documents';
const outputFile = './src/lib/generated-rag.ts';

async function processDocs() {
    console.log("📄 Processing RAG Documents...");

    try {
        await fs.access(documentsDir);
    } catch {
        console.warn("⚠️ No documents directory found. Skipping.");
        await fs.writeFile(outputFile, 'export const ragContent = "";');
        return;
    }

    const files = await fs.readdir(documentsDir);
    let allText = "";

    for (const file of files) {
        const filePath = path.join(documentsDir, file);

        try {
            if (file.endsWith('.pdf')) {
                console.log(`   - Reading PDF: ${file}`);
                const buffer = await fs.readFile(filePath);
                const data = await pdf(buffer);
                // Clean up text slightly to save space
                const cleanText = data.text.replace(/\n\s*\n/g, '\n').trim();
                allText += `\n--- START DOCUMENT: ${file} ---\n${cleanText}\n--- END DOCUMENT ---\n`;
            }
            else if (file.endsWith('.txt') || file.endsWith('.md')) {
                console.log(`   - Reading Text: ${file}`);
                const text = await fs.readFile(filePath, 'utf-8');
                allText += `\n--- START DOCUMENT: ${file} ---\n${text.trim()}\n--- END DOCUMENT ---\n`;
            }
        } catch (err) {
            console.error(`❌ Error processing ${file}:`, err.message);
        }
    }

    // Escape backticks and standard JS escaping for the string content
    const escapedText = allText.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\${/g, '\\${');

    const fileContent = `// Auto-generated by scripts/process-docs.mjs
// Do not edit manually.
export const ragContent = \`${escapedText}\`;
`;

    await fs.writeFile(outputFile, fileContent);
    console.log(`✅ RAG Content generated at ${outputFile} (${allText.length} chars)`);
}

processDocs();
